development:
  adapter: postgresql
  database: database_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: database_pro
  pool: 5
  timeout: 5000